<#
.SYNOPSIS
    Automated destination server setup and SSH key provisioning script for Simply Transfer.

.DESCRIPTION
    Configures a destination host to receive SFTP transfers from Simply Transfer:
    - Verifies or installs OpenSSH Server on the destination host.
    - Generates OpenSSH host keys (ssh-keygen -A) if missing.
    - Discovers or accepts the client's public key (generated by setup-prerequisites.ps1).
    - Generates and hardens destination authorized keys:
      * C:\ProgramData\ssh\administrators_authorized_keys (for Administrator accounts, with strict ACLs)
      * C:\Users\<user>\.ssh\authorized_keys (for Standard user accounts, with strict ACLs)
    - Configures and starts sshd and ssh-agent Windows services (Automatic startup).
    - Configures Windows Defender Firewall inbound rule for Port 22 (SSH).
    - Pre-creates and secures the destination backup storage directory.
    - Generates a portable remote deployment script (deploy-to-remote-dest.ps1) for copying
      to other remote servers (e.g. 192.168.1.100).
    - Generates a comprehensive destination readiness report (dest-prerequisites-report.txt).

.PARAMETER ClientPublicKey
    The OpenSSH public key string (e.g. "ssh-ed25519 AAAAC3Nza...") to authorize on this destination.
    If not specified, the script auto-discovers it from ~/.ssh/id_ed25519.pub or prerequisites-report.txt.

.PARAMETER ClientPublicKeyFile
    Path to a public key file (.pub) to import and authorize.

.PARAMETER DestinationUser
    The Windows username under which SFTP sessions will authenticate. Defaults to the current user ($env:USERNAME).

.PARAMETER DestinationDirectory
    The base directory where transferred files will be deposited. Defaults to "C:\Backups".

.PARAMETER KeyComment
    Comment to embed if a new key pair must be generated. Defaults to "SimplyTransfer-Dest-<ComputerName>".

.PARAMETER SkipFirewall
    Skips configuring Windows Defender Firewall Port 22 rules.

.PARAMETER SkipServiceStart
    Skips starting or restarting the sshd service.

.PARAMETER NoPause
    Suppresses the interactive "Press [Enter] to exit" prompt at the end of execution.

.PARAMETER Elevate
    Relaunches the script in an elevated Administrator session if currently unprivileged.

.EXAMPLE
    # Run right after setup-prerequisites.ps1 to configure destination on the same or staging machine:
    .\dest_prerequisites.ps1

.EXAMPLE
    # Run on a destination server authorizing a specific client public key string:
    .\dest_prerequisites.ps1 -ClientPublicKey "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5..."

.EXAMPLE
    # Authorize for a specific user and custom destination directory:
    .\dest_prerequisites.ps1 -DestinationUser "BackupUser" -DestinationDirectory "D:\SFTP_Data" -Elevate
#>

[CmdletBinding()]
param(
    [string]$ClientPublicKey,
    [string]$ClientPublicKeyFile,
    [string]$DestinationUser = $env:USERNAME,
    [string]$DestinationDirectory = "C:\Backups",
    [string]$KeyComment = "SimplyTransfer-Dest-$env:COMPUTERNAME",
    [switch]$SkipFirewall,
    [switch]$SkipServiceStart,
    [switch]$NoPause,
    [switch]$Elevate
)

$scriptDir = if ($MyInvocation.MyCommand.Path) { Split-Path -Parent $MyInvocation.MyCommand.Path } else { (Get-Location).Path }
if (-not $scriptDir) { $scriptDir = (Get-Location).Path }

# -------------------------------------------------------------------------
# UI & Formatting Helper Functions
# -------------------------------------------------------------------------

function Write-Header {
    param([string]$Title)
    Write-Host ""
    Write-Host ("=" * 65) -ForegroundColor Cyan
    Write-Host "   $Title" -ForegroundColor Cyan
    Write-Host ("=" * 65) -ForegroundColor Cyan
}

function Write-Step {
    param([string]$StepNumber, [string]$Title)
    Write-Host ""
    Write-Host "[$StepNumber] $Title" -ForegroundColor Yellow
}

function Write-Success {
    param([string]$Message)
    Write-Host "  [OK] $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host "  [INFO] $Message" -ForegroundColor Cyan
}

function Write-Warn {
    param([string]$Message)
    Write-Host "  [WARN] $Message" -ForegroundColor Yellow
}

function Write-Fail {
    param([string]$Message)
    Write-Host "  [FAIL] $Message" -ForegroundColor Red
}

function Test-IsAdmin {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Restart-AsAdmin {
    param([string[]]$ScriptArgs)
    Write-Info "Relaunching destination setup script with elevated Administrator privileges..."
    $argList = @("-NoExit", "-ExecutionPolicy", "Bypass", "-File", "`"$PSCommandPath`"")
    if ($ScriptArgs) {
        $argList += $ScriptArgs
    }
    Start-Process powershell.exe -Verb RunAs -ArgumentList $argList
    exit 0
}

# -------------------------------------------------------------------------
# 0. Privilege Check & Auto-Elevation
# -------------------------------------------------------------------------

Write-Header "Simply Transfer - Destination Host & Key Setup Utility"

$isAdmin = Test-IsAdmin

if (-not $isAdmin) {
    if ($Elevate) {
        Restart-AsAdmin -ScriptArgs ($PSBoundParameters.GetEnumerator() | ForEach-Object { "-$($_.Key)" })
    }
    else {
        Write-Warn "Script is running without Administrator elevation."
        Write-Warn "OpenSSH server configuration, administrators_authorized_keys, and firewall rules require Administrator rights."
        Write-Info "To automatically elevate, rerun with: .\dest_prerequisites.ps1 -Elevate"
        Write-Host ""
    }
}
else {
    Write-Success "Running with elevated Administrator privileges."
}

# Summary status tracker
$statusReport = [ordered]@{}

# -------------------------------------------------------------------------
# 1. OpenSSH Server Capability & Installation
# -------------------------------------------------------------------------

Write-Step "1/7" "Verifying OpenSSH Server Capability..."

$sshServerInstalled = $false
try {
    $capability = Get-WindowsCapability -Online -Name "OpenSSH.Server*" -ErrorAction SilentlyContinue
    if ($capability -and $capability.State -eq "Installed") {
        $sshServerInstalled = $true
        Write-Success "OpenSSH Server capability is installed."
        $statusReport["OpenSSH Server Feature"] = "Installed"
    }
    elseif ($capability) {
        Write-Info "OpenSSH Server capability state: $($capability.State)"
        if ($isAdmin) {
            Write-Info "Installing OpenSSH.Server capability via DISM..."
            $result = Add-WindowsCapability -Online -Name $capability.Name -ErrorAction Stop
            if ($result.RestartNeeded) {
                Write-Warn "A Windows reboot may be required to complete OpenSSH Server installation."
            }
            $sshServerInstalled = $true
            Write-Success "OpenSSH Server capability successfully installed."
            $statusReport["OpenSSH Server Feature"] = "Installed (via DISM)"
        }
        else {
            Write-Warn "Administrator rights required to install OpenSSH.Server capability."
            $statusReport["OpenSSH Server Feature"] = "Not Installed (Admin Required)"
        }
    }
}
catch {
    Write-Warn "Could not query Windows Capabilities directly: $($_.Exception.Message)"
}

# Fallback: check sshd.exe on disk
if (-not $sshServerInstalled) {
    $sshdPath = "$env:WINDIR\System32\OpenSSH\sshd.exe"
    if (Test-Path $sshdPath) {
        $sshServerInstalled = $true
        Write-Success "OpenSSH Server binary detected at $sshdPath."
        $statusReport["OpenSSH Server Feature"] = "Installed (Binary Present)"
    }
    else {
        Write-Fail "OpenSSH Server is not installed on this host."
        $statusReport["OpenSSH Server Feature"] = "Missing"
    }
}

# -------------------------------------------------------------------------
# 2. Destination OpenSSH Host Keys Generation
# -------------------------------------------------------------------------

Write-Step "2/7" "Verifying & Generating OpenSSH Server Host Keys..."

$programDataSsh = Join-Path $env:ProgramData "ssh"
if (-not (Test-Path $programDataSsh)) {
    Write-Info "Creating OpenSSH system configuration directory: $programDataSsh"
    New-Item -Path $programDataSsh -ItemType Directory -Force | Out-Null
}

$hostKeyEd25519 = Join-Path $programDataSsh "ssh_host_ed25519_key"
$hostKeyRsa = Join-Path $programDataSsh "ssh_host_rsa_key"
$hostKeysFound = (Test-Path $hostKeyEd25519) -or (Test-Path $hostKeyRsa)

if ($hostKeysFound) {
    Write-Success "OpenSSH Server host keys present in $programDataSsh"
    $statusReport["Host Keys"] = "Verified Existing"
}
else {
    Write-Info "OpenSSH Server host keys not found. Generating default host keys..."
    $keygenExe = "$env:WINDIR\System32\OpenSSH\ssh-keygen.exe"
    if (-not (Test-Path $keygenExe)) {
        $keygenCmd = Get-Command "ssh-keygen.exe" -ErrorAction SilentlyContinue
        if ($keygenCmd) { $keygenExe = $keygenCmd.Source }
    }

    if ($keygenExe -and (Test-Path $keygenExe) -and $isAdmin) {
        try {
            # ssh-keygen -A generates all missing default host keys
            & $keygenExe -A
            if ((Test-Path $hostKeyEd25519) -or (Test-Path $hostKeyRsa)) {
                Write-Success "Generated OpenSSH Server host keys via ssh-keygen -A"
                $statusReport["Host Keys"] = "Generated (ssh-keygen -A)"
            }
            else {
                # Explicitly generate Ed25519 host key
                & $keygenExe -t ed25519 -f "$hostKeyEd25519" -N '""'
                Write-Success "Generated Ed25519 host key: $hostKeyEd25519"
                $statusReport["Host Keys"] = "Generated (Ed25519)"
            }
        }
        catch {
            Write-Warn "Error executing ssh-keygen: $($_.Exception.Message)"
            $statusReport["Host Keys"] = "Generation Error"
        }
    }
    else {
        Write-Warn "Cannot generate host keys without Administrator privileges or ssh-keygen.exe."
        $statusReport["Host Keys"] = "Generation Skipped"
    }
}

# -------------------------------------------------------------------------
# 3. Discover or Obtain Client Public Key
# -------------------------------------------------------------------------

Write-Step "3/7" "Acquiring Client Public Key to Authorize..."

$resolvedPublicKey = $null

# Priority 1: Direct string parameter
if (-not [string]::IsNullOrWhiteSpace($ClientPublicKey)) {
    $resolvedPublicKey = $ClientPublicKey.Trim()
    Write-Success "Using client public key provided via -ClientPublicKey parameter."
}

# Priority 2: Public key file parameter
if (-not $resolvedPublicKey -and -not [string]::IsNullOrWhiteSpace($ClientPublicKeyFile)) {
    if (Test-Path $ClientPublicKeyFile) {
        $resolvedPublicKey = (Get-Content -Path $ClientPublicKeyFile -Raw).Trim()
        Write-Success "Loaded client public key from file: $ClientPublicKeyFile"
    }
    else {
        Write-Warn "Specified -ClientPublicKeyFile was not found: $ClientPublicKeyFile"
    }
}

# Priority 3: Local ~/.ssh/id_ed25519.pub or id_rsa.pub (if run after setup-prerequisites.ps1)
if (-not $resolvedPublicKey) {
    $candidatePubKeys = @(
        (Join-Path $env:USERPROFILE ".ssh\id_ed25519.pub"),
        (Join-Path $env:USERPROFILE ".ssh\id_rsa.pub")
    )
    foreach ($pubPath in $candidatePubKeys) {
        if (Test-Path $pubPath) {
            try {
                $content = (Get-Content -Path $pubPath -Raw).Trim()
                if ($content -match "^ssh-(ed25519|rsa|ecdsa)") {
                    $resolvedPublicKey = $content
                    Write-Success "Discovered local public key generated by setup-prerequisites: $pubPath"
                    break
                }
            }
            catch { }
        }
    }
}

# Priority 4: Look for prerequisites-report.txt in project root or AppData
if (-not $resolvedPublicKey) {
    $candidateReports = @(
        (Join-Path $scriptDir "prerequisites-report.txt"),
        (Join-Path $env:APPDATA "SimplyTransfer\prerequisites-report.txt")
    )
    foreach ($reportPath in $candidateReports) {
        if (Test-Path $reportPath) {
            $lines = Get-Content -Path $reportPath
            $capture = $false
            foreach ($line in $lines) {
                if ($line -match "AUTHORIZED KEY ENTRY") {
                    $capture = $true
                    continue
                }
                if ($capture -and ($line -match "^ssh-(ed25519|rsa|ecdsa)")) {
                    $resolvedPublicKey = $line.Trim()
                    Write-Success "Extracted public key entry from report: $reportPath"
                    break
                }
            }
            if ($resolvedPublicKey) { break }
        }
    }
}

# Priority 5: Interactive prompt or local key pair generation
if (-not $resolvedPublicKey) {
    Write-Warn "No client public key was automatically discovered on this machine."
    Write-Host ""
    Write-Host "  Select an option:" -ForegroundColor Cyan
    Write-Host "  [1] Paste an OpenSSH public key string (e.g. from client machine)" -ForegroundColor White
    Write-Host "  [2] Generate a new Ed25519 SSH key pair on this machine now" -ForegroundColor White
    Write-Host "  [3] Skip key assignment (configure server services only)" -ForegroundColor White
    Write-Host ""

    $choice = ""
    try {
        $choice = Read-Host "  Enter choice [1, 2, or 3] (Default: 2)"
    }
    catch {
        $choice = "2"
    }

    if ($choice -eq "1") {
        $pasted = Read-Host "  Paste Public Key string"
        if (-not [string]::IsNullOrWhiteSpace($pasted)) {
            $resolvedPublicKey = $pasted.Trim()
        }
    }
    elseif ($choice -eq "3") {
        Write-Info "Skipping key authorization step by user request."
    }
    else {
        # Generate new Ed25519 key pair
        $sshDir = Join-Path $env:USERPROFILE ".ssh"
        if (-not (Test-Path $sshDir)) {
            New-Item -Path $sshDir -ItemType Directory -Force | Out-Null
        }
        $newKeyPath = Join-Path $sshDir "id_ed25519"
        $keygenExe = "$env:WINDIR\System32\OpenSSH\ssh-keygen.exe"
        if (-not (Test-Path $keygenExe)) {
            $keygenCmd = Get-Command "ssh-keygen.exe" -ErrorAction SilentlyContinue
            if ($keygenCmd) { $keygenExe = $keygenCmd.Source }
        }

        if ($keygenExe -and (Test-Path $keygenExe)) {
            Write-Info "Generating new Ed25519 key pair ($KeyComment)..."
            & $keygenExe -t ed25519 -C "$KeyComment" -f "$newKeyPath" -N '""'
            if (Test-Path "$newKeyPath.pub") {
                icacls.exe "$newKeyPath" /inheritance:r /grant:r "$($env:USERNAME):(F)" /grant:r "SYSTEM:(F)" | Out-Null
                $resolvedPublicKey = (Get-Content "$newKeyPath.pub" -Raw).Trim()
                Write-Success "Generated new Ed25519 key pair: $newKeyPath"
            }
        }
    }
}

if ($resolvedPublicKey) {
    Write-Info "Public key to authorize:"
    Write-Host "  $resolvedPublicKey" -ForegroundColor White
    $statusReport["Client Public Key"] = "Resolved"
}
else {
    Write-Warn "No public key available to authorize."
    $statusReport["Client Public Key"] = "None"
}

# -------------------------------------------------------------------------
# 4. Generate & Harden Destination Authorized Keys Files
# -------------------------------------------------------------------------

Write-Step "4/7" "Authorizing Public Key on Destination Server..."

$keysAuthorizedCount = 0

if ($resolvedPublicKey) {
    # ---------------------------------------------------------------------
    # 4A. Target 1: C:\ProgramData\ssh\administrators_authorized_keys
    # CRITICAL: Windows OpenSSH ignores C:\Users\<admin>\.ssh\authorized_keys
    # for accounts belonging to the local Administrators group!
    # ---------------------------------------------------------------------
    Write-Info "Configuring Windows OpenSSH administrators_authorized_keys..."
    $adminAuthFile = Join-Path $programDataSsh "administrators_authorized_keys"

    if (-not $isAdmin) {
        Write-Warn "Configuring $adminAuthFile requires Administrator privileges."
        Write-Info "Run with -Elevate to configure administrators_authorized_keys with strict ACLs."
        $statusReport["Administrators Authorized Keys"] = "Requires Elevation (Rerun with -Elevate)"
    }
    else {
        try {
            if (-not (Test-Path $adminAuthFile)) {
                New-Item -Path $adminAuthFile -ItemType File -Force -ErrorAction Stop | Out-Null
            }

            # Check if key is already present
            $existingKeys = @()
            if (Test-Path $adminAuthFile) {
                $existingKeys = Get-Content -Path $adminAuthFile -ErrorAction SilentlyContinue
            }

            if ($existingKeys -notcontains $resolvedPublicKey) {
                Add-Content -Path $adminAuthFile -Value $resolvedPublicKey -Encoding Ascii -Force -ErrorAction Stop
                Write-Success "Appended public key to $adminAuthFile"
            }
            else {
                Write-Success "Public key already present in $adminAuthFile"
            }

            # Explicitly set ownership to BUILTIN\Administrators (*S-1-5-32-544)
            try {
                takeown.exe /F $adminAuthFile /A | Out-Null
            }
            catch { }

            # Apply mandatory strict ACL permissions (disable inheritance, grant Administrators and SYSTEM only via well-known SIDs)
            icacls.exe $adminAuthFile /inheritance:r /grant:r "*S-1-5-32-544:(F)" /grant:r "*S-1-5-18:(F)" | Out-Null
            icacls.exe $adminAuthFile /setowner "*S-1-5-32-544" | Out-Null
            Write-Success "Applied strict NTFS ACLs & ownership to $adminAuthFile (Administrators:F, SYSTEM:F)"

            # Ensure ProgramData\ssh folder also has secure permissions
            icacls.exe $programDataSsh /grant:r "*S-1-5-32-544:(OI)(CI)(F)" /grant:r "*S-1-5-18:(OI)(CI)(F)" | Out-Null

            $statusReport["Administrators Authorized Keys"] = "Configured & Hardened"
            $keysAuthorizedCount++
        }
        catch {
            Write-Warn "Could not configure $adminAuthFile`: $($_.Exception.Message)"
            $statusReport["Administrators Authorized Keys"] = "Failed ($($_.Exception.Message))"
        }
    }

    # ---------------------------------------------------------------------
    # 4B. Target 2: C:\Users\<user>\.ssh\authorized_keys
    # (For Standard / non-admin user accounts)
    # ---------------------------------------------------------------------
    Write-Info "Configuring user-level authorized_keys for user '$DestinationUser'..."
    
    # Resolve user profile directory
    $userProfilePath = $env:USERPROFILE
    if ($DestinationUser -and $DestinationUser -ne $env:USERNAME) {
        $potentialDir = "C:\Users\$DestinationUser"
        if (Test-Path $potentialDir) {
            $userProfilePath = $potentialDir
        }
    }

    $userSshDir = Join-Path $userProfilePath ".ssh"
    $userAuthFile = Join-Path $userSshDir "authorized_keys"

    try {
        if (-not (Test-Path $userSshDir)) {
            New-Item -Path $userSshDir -ItemType Directory -Force | Out-Null
        }

        if (-not (Test-Path $userAuthFile)) {
            New-Item -Path $userAuthFile -ItemType File -Force | Out-Null
        }

        $existingUserKeys = Get-Content -Path $userAuthFile -ErrorAction SilentlyContinue
        if ($existingUserKeys -notcontains $resolvedPublicKey) {
            Add-Content -Path $userAuthFile -Value $resolvedPublicKey -Encoding Ascii -Force
            Write-Success "Appended public key to $userAuthFile"
        }
        else {
            Write-Success "Public key already present in $userAuthFile"
        }

        # Apply strict NTFS ACL permissions for the specific user
        if ($isAdmin) {
            icacls.exe $userSshDir /inheritance:r /grant:r "$($DestinationUser):(OI)(CI)(F)" /grant:r "*S-1-5-18:(OI)(CI)(F)" /grant:r "*S-1-5-32-544:(OI)(CI)(F)" | Out-Null
            icacls.exe $userAuthFile /inheritance:r /grant:r "$($DestinationUser):(F)" /grant:r "*S-1-5-18:(F)" /grant:r "*S-1-5-32-544:(F)" | Out-Null
            Write-Success "Applied strict NTFS ACLs to $userAuthFile ($DestinationUser:F, SYSTEM:F)"
        }
        $statusReport["User Authorized Keys"] = "Configured ($userAuthFile)"
        $keysAuthorizedCount++
    }
    catch {
        Write-Warn "Could not configure $userAuthFile`: $($_.Exception.Message)"
        $statusReport["User Authorized Keys"] = "Failed ($($_.Exception.Message))"
    }
}
else {
    Write-Warn "No public key was authorized. Run with -ClientPublicKey '<key_string>' to authorize."
    $statusReport["Authorized Keys"] = "Skipped"
}

# -------------------------------------------------------------------------
# 5. Configure & Start OpenSSH Server & Agent Services
# -------------------------------------------------------------------------

Write-Step "5/7" "Configuring & Starting OpenSSH Services..."

if (-not $SkipServiceStart -and $isAdmin) {
    # 5A. OpenSSH Server Service (sshd)
    try {
        $sshd = Get-Service -Name "sshd" -ErrorAction SilentlyContinue
        if ($sshd) {
            if ($sshd.StartType -ne "Automatic") {
                Set-Service -Name "sshd" -StartupType Automatic
                Write-Success "Set sshd service StartupType to Automatic."
            }
            if ($sshd.Status -ne "Running") {
                Start-Service -Name "sshd"
                Write-Success "Started sshd Windows Service."
            }
            else {
                # Restart sshd to ensure updated authorized_keys and host keys are re-read
                Restart-Service -Name "sshd" -Force
                Write-Success "Restarted sshd Windows Service to load updated keys."
            }
            $statusReport["sshd Service"] = "Running (Automatic)"
        }
        else {
            Write-Warn "sshd service not found in Service Control Manager."
            $statusReport["sshd Service"] = "Not Found"
        }
    }
    catch {
        Write-Warn "Could not configure/restart sshd service: $($_.Exception.Message)"
        $statusReport["sshd Service"] = "Error ($($_.Exception.Message))"
    }

    # 5B. OpenSSH Authentication Agent Service (ssh-agent)
    try {
        $sshAgent = Get-Service -Name "ssh-agent" -ErrorAction SilentlyContinue
        if ($sshAgent) {
            if ($sshAgent.StartType -ne "Automatic") {
                Set-Service -Name "ssh-agent" -StartupType Automatic
            }
            if ($sshAgent.Status -ne "Running") {
                Start-Service -Name "ssh-agent"
            }
            Write-Success "ssh-agent service configured and running (Automatic)."
            $statusReport["ssh-agent Service"] = "Running (Automatic)"
        }
    }
    catch {
        Write-Warn "Could not configure ssh-agent service: $($_.Exception.Message)"
    }
}
else {
    if (-not $isAdmin) {
        Write-Warn "Skipping service management (Administrator elevation required)."
        $statusReport["sshd Service"] = "Unverified (Non-Elevated)"
    }
    else {
        $statusReport["sshd Service"] = "Skipped"
    }
}

# -------------------------------------------------------------------------
# 6. Windows Firewall Port 22 Configuration
# -------------------------------------------------------------------------

Write-Step "6/7" "Verifying Windows Defender Firewall (Port 22)..."

if (-not $SkipFirewall) {
    $firewallRule = Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue
    if (-not $firewallRule) {
        $firewallRule = Get-NetFirewallRule -DisplayName "OpenSSH Server (sshd)" -ErrorAction SilentlyContinue
    }

    if ($firewallRule) {
        if (-not $firewallRule.Enabled -and $isAdmin) {
            Enable-NetFirewallRule -Name $firewallRule.Name
            Write-Success "Enabled inbound firewall rule: $($firewallRule.DisplayName)"
        }
        else {
            Write-Success "Inbound Port 22 firewall rule is active: $($firewallRule.DisplayName)"
        }
        $statusReport["Firewall Port 22"] = "Allowed"
    }
    else {
        if ($isAdmin) {
            try {
                New-NetFirewallRule -Name "OpenSSH-Server-In-TCP" `
                    -DisplayName "OpenSSH Server (sshd)" `
                    -Enabled True `
                    -Direction Inbound `
                    -Protocol TCP `
                    -Action Allow `
                    -LocalPort 22 | Out-Null
                Write-Success "Created and allowed inbound firewall rule for Port 22."
                $statusReport["Firewall Port 22"] = "Created & Allowed"
            }
            catch {
                Write-Warn "Could not create firewall rule: $($_.Exception.Message)"
                $statusReport["Firewall Port 22"] = "Manual Config Needed"
            }
        }
        else {
            Write-Warn "Firewall rule not found. Administrator rights required to add firewall rules."
            $statusReport["Firewall Port 22"] = "Missing (Admin Required)"
        }
    }
}
else {
    $statusReport["Firewall Port 22"] = "Skipped"
}

# -------------------------------------------------------------------------
# 7. Destination Backup Storage Directory Setup
# -------------------------------------------------------------------------

Write-Step "7/7" "Configuring Destination Storage Directory ($DestinationDirectory)..."

try {
    if (-not (Test-Path $DestinationDirectory)) {
        New-Item -Path $DestinationDirectory -ItemType Directory -Force | Out-Null
        Write-Success "Created destination backup folder: $DestinationDirectory"
    }
    else {
        Write-Success "Destination backup folder exists: $DestinationDirectory"
    }

    # Grant write access to destination user and Administrators
    if ($isAdmin) {
        icacls.exe "$DestinationDirectory" /grant:r "$($DestinationUser):(OI)(CI)(M)" /grant:r "Administrators:(OI)(CI)(F)" | Out-Null
        Write-Success "Configured write permissions on $DestinationDirectory for '$DestinationUser'"
    }
    $statusReport["Destination Directory"] = "Ready ($DestinationDirectory)"
}
catch {
    Write-Warn "Could not verify/create destination directory: $($_.Exception.Message)"
    $statusReport["Destination Directory"] = "Error ($($_.Exception.Message))"
}

# -------------------------------------------------------------------------
# Generate Standalone Remote Deployment Script (for remote servers)
# -------------------------------------------------------------------------

if ($resolvedPublicKey) {
    try {
        $deployScriptPath = Join-Path $scriptDir "deploy-to-remote-dest.ps1"
        $deployScriptContent = @"
# ==============================================================================
# Simply Transfer - Remote Destination Key Assignment Script
# Run this script on your DESTINATION SERVER in an Administrator PowerShell prompt.
# ==============================================================================

#Requires -RunAsAdministrator

`$key = "$resolvedPublicKey"
`$user = "$DestinationUser"
`$destDir = "$DestinationDirectory"

Write-Host ">>> Configuring Destination Server for Simply Transfer <<<" -ForegroundColor Cyan

# 1. Ensure OpenSSH ProgramData directory exists
`$programDataSsh = "`$env:ProgramData\ssh"
New-Item -ItemType Directory -Force -Path `$programDataSsh | Out-Null
icacls.exe `$programDataSsh /grant:r "*S-1-5-32-544:(OI)(CI)(F)" /grant:r "*S-1-5-18:(OI)(CI)(F)" | Out-Null

# 2. Configure administrators_authorized_keys (for Windows Administrator accounts)
`$adminAuth = "`$programDataSsh\administrators_authorized_keys"
Add-Content -Path `$adminAuth -Value `$key -Encoding Ascii -Force
try { takeown.exe /F `$adminAuth /A | Out-Null } catch { }
icacls.exe `$adminAuth /inheritance:r /grant:r "*S-1-5-32-544:F" /grant:r "*S-1-5-18:F" | Out-Null
icacls.exe `$adminAuth /setowner "*S-1-5-32-544" | Out-Null
Write-Host "[OK] Configured `$adminAuth" -ForegroundColor Green

# 3. Configure user authorized_keys (for Standard accounts)
`$userSshDir = "`$env:USERPROFILE\.ssh"
New-Item -ItemType Directory -Force -Path `$userSshDir | Out-Null
`$userAuth = "`$userSshDir\authorized_keys"
Add-Content -Path `$userAuth -Value `$key -Encoding Ascii -Force
icacls.exe `$userSshDir /inheritance:r /grant:r "`$(`$user):(OI)(CI)(F)" /grant:r "*S-1-5-18:(OI)(CI)(F)" /grant:r "*S-1-5-32-544:(OI)(CI)(F)" | Out-Null
icacls.exe `$userAuth /inheritance:r /grant:r "`$(`$user):F" /grant:r "*S-1-5-18:F" /grant:r "*S-1-5-32-544:F" | Out-Null
Write-Host "[OK] Configured `$userAuth" -ForegroundColor Green

# 4. Pre-create destination backup directory
New-Item -ItemType Directory -Force -Path `$destDir | Out-Null
icacls.exe `$destDir /grant:r "`$(`$user):(OI)(CI)(M)" /grant:r "*S-1-5-32-544:(OI)(CI)(F)" | Out-Null
Write-Host "[OK] Pre-created backup folder: `$destDir" -ForegroundColor Green

# 5. Restart sshd service
Set-Service -Name "sshd" -StartupType Automatic -ErrorAction SilentlyContinue
Restart-Service sshd -ErrorAction SilentlyContinue
Write-Host "[OK] Restarted sshd service." -ForegroundColor Green

Write-Host ""
Write-Host "Destination configuration complete! Simply Transfer can now authenticate." -ForegroundColor Cyan
"@

        Set-Content -Path $deployScriptPath -Value $deployScriptContent -Encoding UTF8
        Write-Success "Generated remote deployment script: $deployScriptPath"
        $statusReport["Remote Deploy Script"] = "Generated ($deployScriptPath)"
    }
    catch {
        Write-Warn "Could not write remote deploy script: $($_.Exception.Message)"
    }
}

# -------------------------------------------------------------------------
# Audit Report & Summary
# -------------------------------------------------------------------------

try {
    $reportTimestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $reportBuilder = New-Object System.Text.StringBuilder
    [void]$reportBuilder.AppendLine("================================================================================")
    [void]$reportBuilder.AppendLine("         SIMPLY TRANSFER - DESTINATION PREREQUISITES & KEY AUDIT REPORT         ")
    [void]$reportBuilder.AppendLine("================================================================================")
    [void]$reportBuilder.AppendLine("Generated:  $reportTimestamp")
    [void]$reportBuilder.AppendLine("Computer:   $env:COMPUTERNAME")
    [void]$reportBuilder.AppendLine("User:       $env:USERDOMAIN\$env:USERNAME")
    [void]$reportBuilder.AppendLine("Privilege:  $(if ($isAdmin) { 'Administrator (Elevated)' } else { 'Standard User' })")
    [void]$reportBuilder.AppendLine("")
    [void]$reportBuilder.AppendLine("--------------------------------------------------------------------------------")
    [void]$reportBuilder.AppendLine("1. DESTINATION READINESS STATUS")
    [void]$reportBuilder.AppendLine("--------------------------------------------------------------------------------")
    foreach ($entry in $statusReport.GetEnumerator()) {
        $line = ("- " + $entry.Key.PadRight(34) + ": " + $entry.Value)
        [void]$reportBuilder.AppendLine($line)
    }
    [void]$reportBuilder.AppendLine("")
    [void]$reportBuilder.AppendLine("--------------------------------------------------------------------------------")
    [void]$reportBuilder.AppendLine("2. AUTHORIZED CLIENT PUBLIC KEY")
    [void]$reportBuilder.AppendLine("--------------------------------------------------------------------------------")
    if ($resolvedPublicKey) {
        [void]$reportBuilder.AppendLine($resolvedPublicKey)
    }
    else {
        [void]$reportBuilder.AppendLine("No client public key was provided or found.")
    }
    [void]$reportBuilder.AppendLine("")
    [void]$reportBuilder.AppendLine("--------------------------------------------------------------------------------")
    [void]$reportBuilder.AppendLine("3. RECOMMENDED SIMPLY TRANSFER PROFILE CONFIGURATION")
    [void]$reportBuilder.AppendLine("--------------------------------------------------------------------------------")
    
    # Determine local IP addresses for easy profile setup
    $localIps = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | 
        Where-Object { $_.InterfaceAlias -notmatch "Loopback|vEthernet" -and $_.IPAddress -notlike "169.254*" } | 
        Select-Object -ExpandProperty IPAddress

    $ipDisplay = if ($localIps) { $localIps -join " or " } else { "<Destination_Host_IP>" }
    [void]$reportBuilder.AppendLine("Host / IP Address    : $ipDisplay")
    [void]$reportBuilder.AppendLine("Port                 : 22")
    [void]$reportBuilder.AppendLine("Username             : $DestinationUser")
    [void]$reportBuilder.AppendLine("Destination Directory: $DestinationDirectory")
    [void]$reportBuilder.AppendLine("Private Key (on client PC) : %USERPROFILE%\.ssh\id_ed25519")
    [void]$reportBuilder.AppendLine("================================================================================")

    $destReportPath = Join-Path $scriptDir "dest-prerequisites-report.txt"
    Set-Content -Path $destReportPath -Value $reportBuilder.ToString() -Encoding UTF8
    Write-Success "Destination audit report saved: $destReportPath"
}
catch {
    Write-Warn "Could not write destination audit report: $($_.Exception.Message)"
}

# -------------------------------------------------------------------------
# Final Summary Output
# -------------------------------------------------------------------------

Write-Header "Destination Server Readiness Summary"

$statusReport.GetEnumerator() | ForEach-Object {
    $key = $_.Key.PadRight(34)
    $val = $_.Value
    if ($val -match "Installed|Running|Ready|Allowed|Verified|Generated|Created|Configured") {
        Write-Host "  $key : " -NoNewline
        Write-Host "$val" -ForegroundColor Green
    }
    elseif ($val -match "Optional|Disabled|Skipped") {
        Write-Host "  $key : " -NoNewline
        Write-Host "$val" -ForegroundColor Gray
    }
    else {
        Write-Host "  $key : " -NoNewline
        Write-Host "$val" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. If configuring a remote server (e.g. 192.168.1.100), run:" -ForegroundColor White
Write-Host "     .\deploy-to-remote-dest.ps1 on that server as Administrator." -ForegroundColor Yellow
Write-Host "  2. In Simply Transfer, click '⚡ Validate Connection' to confirm authentication." -ForegroundColor White
Write-Host ""

if (-not $NoPause) {
    Write-Host "------------------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "Destination setup complete. Press [Enter] to exit..." -ForegroundColor Cyan -NoNewline
    try {
        [void][System.Console]::ReadLine()
    }
    catch {
        Read-Host | Out-Null
    }
}
